language: c
env:
  - TRAVIS_PYTHON_VERSION=2.7
os:
  - linux
jobs:
  include:
    - stage: galaxy
      env:
        - TESTGALAXY="1"
        - TRAVIS_PYTHON_VERSION=2.7

# Setup anaconda
before_install:
  #- if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_PYTHON_VERSION" == "2.7" ]] ; then pip install virtualenv --user ; fi
  #- if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_PYTHON_VERSION" == "2.7" ]] ; then virtualenv foo; source foo/bin/activate; pip install planemo ; deactivate ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_PYTHON_VERSION" == "2.7" ]] ; then curl https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -o miniconda.sh ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_PYTHON_VERSION" == "3.6" ]] ; then curl https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -o miniconda.sh ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" && "$TRAVIS_PYTHON_VERSION" == "2.7" ]] ; then curl https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh -o miniconda.sh ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" && "$TRAVIS_PYTHON_VERSION" == "3.6" ]] ; then curl https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -o miniconda.sh ; fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda

  # Useful for debugging any issues with conda
  - conda info -a

# Install packages
install:
  - conda install --yes -f -c conda-forge python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib nose flake8 plotly==2.0.12
  - conda install --yes -c bioconda pysam pyBigWig py2bit planemo
  - python setup.py install

# command to run tests
script:
  - if [[ ${TESTGALAXY:-"2"} == "2" ]] ; then flake8 . --exclude=.venv,.build,foo,build,deeptoolsintervals/__init__.py --ignore=E501,F403,E402,F999,F405,E722 ; fi
  - if [[ ${TESTGALAXY:-"2"} == "2" ]] ; then export owd=`pwd` ; fi
  - if [[ ${TESTGALAXY:-"2"} == "2" ]] ; then cd ~/ && nosetests --with-doctest -sv deeptools ; fi
  - if [[ ${TESTGALAXY:-"2"} == "2" && "$TRAVIS_OS_NAME" == "linux" ]] ; then nosetests --with-doctest -sv deeptoolsintervals ; fi
  - if [[ ${TESTGALAXY:-"2"} == "2" ]] ; then cd ${owd} ; fi
  #- if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_PYTHON_VERSION" == "2.7" && ${TESTGALAXY:-"0"} == "1" ]] ; then /home/travis/build/deeptools/deepTools/foo/bin/planemo lint galaxy/wrapper/ ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_PYTHON_VERSION" == "2.7" && ${TESTGALAXY:-"0"} == "1" ]] ; then ./.planemo.sh ; fi
sudo: false

services:
  - postgresql
